apiVersion: v1
kind: Service
metadata:
  labels:
    app: text-generation
  name: text-generation
spec:
  type: LoadBalancer
  ports:
  - name: text-generation-service
    port: 5000
    targetPort: 5000
  selector:
    app: text-generation
  